# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:12
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pc',
            field=models.FileField(default=builtins.all, upload_to=''),
        ),
    ]
