# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_account_profile_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pc',
            field=models.FileField(upload_to=''),
        ),
    ]
