# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 11:54
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20170612_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default=builtins.all, upload_to=''),
        ),
    ]
