# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20170612_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_pc',
        ),
    ]
