# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_remove_account_profile_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
