# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20170612_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_notifications', to='myblog.Answer')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myblog.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='media'),
        ),
    ]
