# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20170613_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='comment',
            new_name='answer',
        ),
    ]
