# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_auto_20170613_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='field',
            field=models.CharField(choices=[('Physics ', 'PHY'), ('Chemistry', 'CHEM'), ('Mathematics', 'MATH'), ('Biology', 'BIO'), ('Computer', 'CS'), ('History', 'HIS'), ('Economics', 'ECON'), ('Literature', 'LIT'), ('Geography', 'GEO'), ('Entrepreneurship', 'ENT')], default='all', max_length=100),
        ),
    ]
