# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_auto_20170613_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
