# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_auto_20170704_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
