# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_remove_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('field', models.CharField(choices=[('Chemistry', 'CHEM'), ('Physics ', 'PHY'), ('Mathematics', 'MATH')], default='all', max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
