# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0024_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='field',
            field=models.CharField(choices=[('Science', 'science'), ('Arts ', 'arts'), ('skills', 'skills')], default='all', max_length=100),
        ),
    ]
