# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0028_school_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='School_name',
        ),
    ]
