# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0029_remove_school_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='p_box',
            new_name='school_name',
        ),
    ]
