# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0031_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user_last_name',
            new_name='user_lastname',
        ),
        migrations.AddField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
