# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0033_remove_teacher_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=245, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
