# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0038_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.ImageField(blank=True, upload_to='You/media/uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pc',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
    ]
