# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0039_auto_20170713_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pc',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
