# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0040_auto_20170713_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
