# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0045_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/%y%m%d')),
                ('age', models.BooleanField()),
            ],
        ),
    ]
