# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0046_player_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
