# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0048_auto_20170714_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pc',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
