# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0053_auto_20170715_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, default=True, upload_to='documents/'),
        ),
    ]
