# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0056_auto_20170715_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
