# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0072_auto_20170725_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
        migrations.AlterField(
            model_name='answer',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myblog.Post'),
        ),
    ]
